/**
 * Restores plaintext content from encrypted files for local development.
 *
 * Usage:
 *   ENCRYPT_PASSWORD=secret node scripts/decrypt.mjs
 *   node scripts/decrypt.mjs --password secret
 *
 * Reads from committed encrypted locations, writes plaintext to data/ (gitignored):
 *   - src/content/tasks/**\/*.enc.md    → data/content/tasks/**\/*.md
 *   - src/content/posts/**\/*.enc.md    → data/content/posts/**\/*.md
 *   - src/content/descriptions/*.enc.md → data/content/descriptions/*.md
 *   - data-encrypted/projects/*.enc.json → data/projects/*.json
 *   - public/photos/**\/*.enc           → public/photos/**\/*.jpg (original deleted)
 *
 * Encrypted files are NOT deleted — they are committed to git.
 * Reads salt from public/enc/config.json (generated by encrypt.mjs).
 */

import { webcrypto } from 'crypto';
import { readFileSync, writeFileSync, existsSync, readdirSync, unlinkSync, mkdirSync } from 'fs';
import { join, resolve, dirname, basename } from 'path';
import { fileURLToPath } from 'url';
import matter from 'gray-matter';

const { subtle } = webcrypto;
const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// --- crypto ---

async function deriveKey(password, saltHex) {
  const raw = await subtle.importKey(
    'raw',
    new TextEncoder().encode(password),
    'PBKDF2',
    false,
    ['deriveKey'],
  );
  return subtle.deriveKey(
    {
      name: 'PBKDF2',
      salt: Buffer.from(saltHex, 'hex'),
      iterations: 300_000,
      hash: 'SHA-256',
    },
    raw,
    { name: 'AES-GCM', length: 256 },
    false,
    ['decrypt'],
  );
}

async function decryptData(key, envelope) {
  const iv = Buffer.from(envelope.iv, 'hex');
  const ct = Buffer.from(envelope.data, 'base64');
  return subtle.decrypt({ name: 'AES-GCM', iv }, key, ct);
}

// --- fs helpers ---

function walkDir(dir) {
  if (!existsSync(dir)) return [];
  const results = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) results.push(...walkDir(full));
    else results.push(full);
  }
  return results;
}

// --- main ---

const password =
  process.env.ENCRYPT_PASSWORD ||
  (() => {
    const idx = process.argv.indexOf('--password');
    return idx !== -1 ? process.argv[idx + 1] : null;
  })();

if (!password) {
  console.error('Error: set ENCRYPT_PASSWORD env var or pass --password <pass>');
  process.exit(1);
}

const configPath = join(ROOT, 'public', 'enc', 'config.json');
if (!existsSync(configPath)) {
  console.error('Error: public/enc/config.json not found. Run encrypt.mjs first.');
  process.exit(1);
}

const { salt: saltHex } = JSON.parse(readFileSync(configPath, 'utf-8'));
console.log('Decrypting content…');

let key;
try {
  key = await deriveKey(password, saltHex);
} catch (e) {
  console.error('Key derivation failed:', e.message);
  process.exit(1);
}

// 1. Content MD files — src/content/**/*.enc.md → data/content/**/*.md
const srcContentBase = join(ROOT, 'src', 'content');
const dataContentBase = join(ROOT, 'data', 'content');
for (const file of walkDir(srcContentBase).filter((f) => f.endsWith('.enc.md'))) {
  const raw = readFileSync(file, 'utf-8');
  const parsed = matter(raw);
  if (!parsed.data.enc_body) continue;
  try {
    const plain = await decryptData(key, parsed.data.enc_body);
    const body = new TextDecoder().decode(plain);
    delete parsed.data.enc_body;
    const rel = file.slice(srcContentBase.length + 1); // e.g. 'tasks/proj/ulid.enc.md'
    const plainFile = join(dataContentBase, rel.replace(/\.enc\.md$/, '.md'));
    mkdirSync(dirname(plainFile), { recursive: true });
    // descriptions had no original frontmatter — write body only
    const isDescription = rel.startsWith('descriptions/');
    writeFileSync(plainFile, isDescription ? body : matter.stringify(body, parsed.data));
    console.log(`  decrypted: ${rel} → ${plainFile.replace(ROOT + '/', '')}`);
  } catch {
    console.error(`  ERROR decrypting ${file.replace(ROOT + '/', '')} — wrong password?`);
    process.exit(1);
  }
}

// 2. Project JSONs — data-encrypted/projects/*.enc.json → data/projects/*.json
const encProjectsDir = join(ROOT, 'data-encrypted', 'projects');
const dataProjectsDir = join(ROOT, 'data', 'projects');
mkdirSync(dataProjectsDir, { recursive: true });
const ENCRYPTED_PROJECT_FIELDS = ['title', 'stage', 'started_at', 'last_activity_at', 'last_task_id', 'last_post_id', 'home_description'];
for (const file of walkDir(encProjectsDir).filter((f) => f.endsWith('.enc.json'))) {
  const proj = JSON.parse(readFileSync(file, 'utf-8'));
  const hasAnyEnc = ENCRYPTED_PROJECT_FIELDS.some((f) => proj[`enc_${f}`]);
  if (!hasAnyEnc) continue;
  try {
    for (const field of ENCRYPTED_PROJECT_FIELDS) {
      const encField = `enc_${field}`;
      if (proj[encField]) {
        const plain = await decryptData(key, proj[encField]);
        proj[field] = new TextDecoder().decode(plain);
        delete proj[encField];
      }
    }
    const plainFile = join(dataProjectsDir, basename(file).replace(/\.enc\.json$/, '.json'));
    writeFileSync(plainFile, JSON.stringify(proj, null, 2) + '\n');
    console.log(`  decrypted: ${basename(file)} → ${basename(plainFile)}`);
  } catch {
    console.error(`  ERROR decrypting ${basename(file)} — wrong password?`);
    process.exit(1);
  }
}

// 3. Images — public/photos/**/*.enc → *.jpg (encrypted file deleted)
for (const subdir of ['home_page', 'covers']) {
  const imgDir = join(ROOT, 'public', 'photos', subdir);
  for (const file of walkDir(imgDir).filter((f) => f.endsWith('.enc'))) {
    const envelope = JSON.parse(readFileSync(file, 'utf-8'));
    try {
      const plain = await decryptData(key, envelope);
      writeFileSync(file.replace(/\.enc$/, '.jpg'), Buffer.from(plain));
      unlinkSync(file);
      console.log(`  decrypted image: ${file.replace(ROOT + '/', '')}`);
    } catch {
      console.error(`  ERROR decrypting image ${basename(file)} — wrong password?`);
      process.exit(1);
    }
  }
}

console.log('Done. data/ restored. Run pnpm generate then pnpm encrypt before committing.');
